# Generated by Django 5.1.7 on 2025-03-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_status_alter_task_deadline_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To do', 'ожидание'), ('in_progress', 'В процессе'), ('In review', 'На рассмотрении'), ('Done', 'Выполнено')], default='pending', max_length=20),
        ),
    ]
